# Generated by Django 3.2.8 on 2021-10-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
    ]
